[functions]
  directory = "api"
  included_files = ["wp/**"]
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/index/:splat"
  status = 200
[template.environment]
  DATABASE = "workbench91"
  USERNAME = "workbench91_owner"
  PASSWORD = "tx3aLBweiSh9"
  HOST = "ep-long-fog-a57kbosv.us-east-2.aws.neon.tech"